# Generated by Django 4.1.7 on 2023-03-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_body_post_date_created_post_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
